name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 12.16.2
          registry-url: 'https://registry.npmjs.org'
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: install roblox-ts
        run: npm i -g roblox-ts
      - name: install local npm packages
        run: npm i --production=false
      - name: publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: clean-up package output
        run: rm -rf ./out
      - name: compile typescript code for model
        run: rbxtsc --type=model
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo, run-in-roblox)
        run: foreman install
      - name: run rojo build
        run: rojo build -o ./touch-screen-joysticks-${{ steps.package-version.outputs.current-version }}.rbxmx ./standalone-model.project.json
      - name: create-release
        uses: actions/create-release@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.package-version.outputs.current-version }}
          tag_name: ${{ steps.package-version.outputs.current-version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload rbxmx file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./touch-screen-joysticks-${{ steps.package-version.outputs.current-version }}.rbxmx
          asset_name: touch-screen-joysticks-${{ steps.package-version.outputs.current-version }}.rbxmx
          asset_content_type: form
      - name: upload rbxmx file to Roblox
        run: |
          cd ./scripts
          python upload_model.py -a ${{ secrets.ASSET_ID }} -f ../touch-screen-joysticks-${{ steps.package-version.outputs.current-version }}.rbxmx -r "${{ secrets.UPLOADER_BOT_ROBLOSECURITY }}"
          cd ..
      - name: prepare wally package contents
        run: |
          mkdir -p ~/temp/touch-screen-joysticks
          cp -r ./{include,out} ~/temp/touch-screen-joysticks/
          cp ./{CHANGELOG.md,LICENSE,README.md,wally.lock,wally.toml} ~/temp/touch-screen-joysticks/
          cp ./standalone-model.project.json ~/temp/touch-screen-joysticks/default.project.json
          mkdir ~/temp/touch-screen-joysticks/node_modules
          cp -r ./node_modules/@rbxts ~/temp/touch-screen-joysticks/node_modules/
      - name: prepare wally auth
        run: |
          mkdir ~/.wally
          echo -e '${{ secrets.WALLY_AUTH }}' > ~/.wally/auth.toml
      - name: publish wally package
        run: wally publish --project-path ~/temp/touch-screen-joysticks/
