name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install npm packages
        uses: bahmutov/npm-install@v1
      - name: run eslint
        run: npm run eslint
      - name: install selene
        run: cargo install selene
      - name: run selene
        run: selene ./tests/src/
  unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: download run-in-roblox
        run: Invoke-WebRequest -Uri "${{ secrets.RUNINROBLOXDOWNLOAD }}" -OutFile run-in-roblox.exe
      - run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/install.py" -OutFile install.py
      - run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/GlobalSettings_13.xml" -OutFile GlobalSettings_13.xml
      - run: pip install wget psutil
      - run: python install.py "${{ secrets.ROBLOSECURITY }}"
      - name: install roblox-ts
        run: npm i roblox-ts
      - name: compile main typescript code
        run: npx roblox-ts
      - name: compile test typescript code
        run: |
          mkdir out
          npx roblox-ts
        working-directory: .\\tests
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo)
        run: foreman install
      - name: run rojo build
        run: rojo build -o .\\tests\\build.rbxlx .\\tests\\
      - run: Start-Job -FilePath .\\take_screenshots.ps1
      - run: |
          Start-Job -FilePath .\\take_screenshots.ps1
          .\\run-in-roblox.exe --place .\\tests\\build.rbxlx --script .\\tests\\spec.lua
        if: always()
      - run: ls
        if: always()
      - run: ls .\\screenshots\\
        if: always()
      - uses: actions/upload-artifact@v1
        with:
          name: screenshots.zip
          path: .\\screenshots
        if: always()
